### ISSUE TITLE
examples/basic_pattern_search.py seems not to work.

### ISSUE THREAD

**Issue by y-ich** [ugoertz/kombilo#1]
Hi.

I tried to use examples/basic_pattern_search.py by changing DB-related path, but failed with the following error messages.

    Traceback (most recent call last):
      File "basic_pattern_search.py", line 119, in <module>
        print K.patternSearchDetails()
      File "/usr/local/lib/python2.7/site-packages/kombilo/kombiloNG.py", line 1358, in patternSearchDetails
        t.append(_('Fixed Color') + ': %s\n' % (_('Yes') if self.fixedColorVar.get() else _('No')))
    AttributeError: 'KEngine' object has no attribute 'fixedColorVar'

I made sure by taking a look source code that certainly KEngine object has no attribute fixedColorVar, rather the attribute is defined in App in kombilo.py.
'fixedAnchorVar', 'nextMoveVar', 'moveLimit', and 'searchInVariations' are also problems.

I succeeded basic_pattern_search.py by commenting out related codes in kombiloNG.py, but I don't think that it is a right way.

Could you fix them?
Thanks.

**Comment by ugoertz** [comment]
Thank you for raising this issue! It should be fixed now.

**Comment by y-ich** [comment]
Thank you for your quick treatment!

One naive question. The method 'sgf_tree' also uses fixedColorVar, etc. Isn't it cause any problems?
I think that it is no problems if sgf_tree is called only by App instance, not KEngine.

And one more request. Sorry to bother you.
Could you update your pip repository, too? (since I am using kombilo via pip...)

Thank you!

**Comment by ugoertz** [comment]
Thanks for re-raising this. I hope it's really fixed now. I will upload a new version to PyPI soon.

(You can also git clone the repository and do `pip install -e .` in that directory to install kombilo using pip from your local version.)

**Comment by y-ich** [comment]
Thank you for the information about pip!

**Comment by y-ich** [comment]
Sorry to bother you again...^^

I tried pip specified by git repository and failed.

setup.py includes kombilo/libkombilo/libkombilo_wrap.cxx in sources but .gitignore prevents to treat this file as the one in the repository.

**Comment by ugoertz** [comment]
You are right ... the files `kombilo/libkombilo/libkombilo_wrap.cxx` and `kombilo/libkombilo.py` are required but not in the repository. They can be produced by SWIG (see the [documentation](https://dl.u-go.net/kombilo/doc/manual.html#development), but note that for the master branch a newer version of SWIG is required than the one currently packaged within Ubuntu).

Maybe it is better to add these files to the source repository?

**Comment by y-ich** [comment]
What I am doing now is deploying an app using your kombilo on heroku (PaaS).
So updating SWIG on heroku may be a little troublesome.
I will appreciate you if you add necessary files for pip installation^^

**Comment by ugoertz** [comment]
Sounds interesting. I added the SWIG produced files to the repository (both the master branch and the v0.8 branch, so you could choose which one you want to work with).

**Comment by y-ich** [comment]
Now I succeeded in installing kombilo(master).

Thank you so much!
